apiVersion: v2
name: guacamole-broker
description: Session Broker for Apache Guacamole - manages VNC container lifecycle
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - guacamole
  - vnc
  - broker
  - session
  - kubernetes
home: https://github.com/MaximeWewer/guacamole-webapp-gateway
sources:
  - https://github.com/MaximeWewer/guacamole-webapp-gateway
maintainers:
  - name: Maxime Wewer
    url: https://github.com/MaximeWewer
