{{- if and .Values.apiKey.value (not .Values.apiKey.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guacamole-webapp-gateway.fullname" . }}-api-key
  labels:
    {{- include "guacamole-webapp-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.apiKey.value | b64enc | quote }}
{{- end }}
---
{{- if not .Values.guacamole.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guacamole-webapp-gateway.fullname" . }}-guacamole
  labels:
    {{- include "guacamole-webapp-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.guacamole.adminPassword | b64enc | quote }}
{{- end }}
---
{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guacamole-webapp-gateway.fullname" . }}-database
  labels:
    {{- include "guacamole-webapp-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.database.password | b64enc | quote }}
{{- end }}
---
{{- if and .Values.vault.enabled (not .Values.vault.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guacamole-webapp-gateway.fullname" . }}-vault
  labels:
    {{- include "guacamole-webapp-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.vault.token }}
  token: {{ .Values.vault.token | b64enc | quote }}
  {{- end }}
  {{- if .Values.vault.roleId }}
  role-id: {{ .Values.vault.roleId | b64enc | quote }}
  {{- end }}
  {{- if .Values.vault.secretId }}
  secret-id: {{ .Values.vault.secretId | b64enc | quote }}
  {{- end }}
{{- end }}
